don't depend on run-parts
under centos/rhel < 7, run-parts has a bunch of dependencies, so replace
it with a very small shell script.

diff --git a/runit/1 b/runit/1
--- a/runit/1
+++ b/runit/1
@@ -1,4 +1,20 @@
 #!/bin/sh
+# Run initialization scripts in /etc/runit/sysinit.  Exit 
+# value of this script is 1 if any of the sysinit scripts
+# fails, 0 otherwise.
 
-exec /usr/bin/run-parts /etc/runit/sysinit
+RETVAL=0
+
+echo "start running system initialization scripts."
+
+for script in /etc/runit/sysinit/*; do
+	if [ -f "$script" ] && [ -x "$script" ]; then
+		echo "  $script"
+		$script || RETVAL=1
+	fi
+done
+
+echo "finished running system initialization scripts."
+
+exit $RETVAL
 
